name: Build Raw-Xml

on:
  push:
    paths:
      - 'src/VsLocalizedIntellisense.Raw/**/'
      - '.github/workflows/build-raw.yml'
  pull_request:
    paths:
      - 'src/VsLocalizedIntellisense.Raw/**/'
      - '.github/workflows/build-raw.yml'

env:
  DOTNET_VERSION: 8.0.x

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            src

      - name: <Setup> .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: <Test> VsLocalizedIntellisense.Raw.Test
        shell: bash
        run: |
          cd src/VsLocalizedIntellisense.Raw/VsLocalizedIntellisense.Raw.Test
          dotnet test
