name: Build Pages [PR]

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build:
    name: Build
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/_build-pages.yml
