name: Lint Intellisense

on:
  push:
    paths:
      - 'work-intellisense/**/*'
      - 'raw-intellisense/**/*'
      - '.github/workflows/lint-intellisense.yml'
  pull_request:
    paths:
      - 'work-intellisense/**/*'
      - 'raw-intellisense/**/*'
      - '.github/workflows/lint-intellisense.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: XML

    runs-on: ubuntu-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v4

      - name: <Install> xmllint
        run: sudo apt-get install -y libxml2-utils


      - name: <Lint> XML (work-intellisense)
        run: |
          for XML in `find work-intellisense -type f -name '*.xml'`; do
            echo "${XML}"
            xmllint --noout "${XML}"
          done

      - name: <Lint> XML (raw-intellisense)
        run: |
          for XML in `find raw-intellisense -type f -name '*.xml'`; do
            echo "${XML}"
            xmllint --noout "${XML}"
          done
